apiVersion: v1
entries:
  jenkins-operator:
  - apiVersion: v1
    appVersion: 0.2.2
    created: "2019-09-19T14:22:54.757957741+02:00"
    description: Kubernetes native operator which fully manages Jenkins on Kubernetes
    digest: b0074d3ded2fdaad529c9079503eb82bb9c8cfb90fd8b60d09c8d9899f36d78f
    name: jenkins-operator
    urls:
    - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart/jenkins-operator/jenkins-operator-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v1
    appVersion: 0.2.0
    created: "2019-09-19T14:22:54.758377827+02:00"
    description: Kubernetes native operator which fully manages Jenkins on Kubernetes
    digest: d5828cba35e435fc6526d235ec98b3ffdb8d6ed20b82c953a81a5c1f660d1fb3
    name: jenkins-operator
    urls:
    - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart/jenkins-operator/jenkins-operator-0.0.1.tgz
    version: 0.0.1
generated: "2019-09-19T14:22:54.757340801+02:00"
