apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-certificate
  namespace: {{ .Release.Namespace }}
spec:
  duration: 2160h 
  renewBefore: 360h
  secretName: webhook-server-cert
  dnsNames:
  - webhook-service.{{ .Release.Namespace }}.svc 
  - webhook-service.{{ .Release.Namespace }}.svc.cluster.local 
  issuerRef:
    kind: Issuer
    name: selfsigned

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}

---
