language: go
sudo: false

env:
  global:
    - GO111MODULE=on

go:
- 1.12.x
- master

matrix:
  fast_finish: true
  allow_failures:
  - go: master

before_install:
- go get -u github.com/golang/lint/golint
- make go-dependencies

script:
- make verify

cache:
  directories:
    - vendor