language: go
sudo: false

go:
- 1.12.x
- master

matrix:
  fast_finish: true
  allow_failures:
  - go: master

before_install:
- go get golang.org/x/lint/golint
- make go-dependencies

script:
- make verify

cache:
  directories:
    - vendor