apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example-8
  namespace: default 
spec:
  configurationAsCode:
    configurations: []
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  ValidateSecurityWarnings: true
  master:
    disableCSRFProtection: false
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.277.4-lts-alpine
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 500Mi
    plugins:
    - name: mailer
      version: "1.19"
    - name: script-security
      version: "1.18"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"    
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: google-login 
      version: "1.2"
    - name: credentials
      version: "2.1"
    - name: ssh-credentials
      version: "1.1"
    - name: junit 
      version: "1.2"
    - name: matrix-project
      version: "1.1"
    - name: git-client
      version: "2.8.4" 
    - name: pipeline-model-definition
      version: "1.3.0"
    - name: favorite
      version: "2"
    - name: workflow-cps
      version: "2"
    
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
